### PR TITLE
Build Omnibus against alpha releases as well as mainline releases

### PR DESCRIPTION
**Pull request by evantahler**

### CODE REVIEW

**Comment by evantahler** [comment]
Github action updated to the proper, most recent, alpha version https://github.com/grouparoo/omnibus/runs/2935274516?check_suite_focus=true

**Comment by evantahler** [comment]
Alpha versions up on Dockerhub.

Screen Shot 2021-06-28 at 12 14 49 PM

**Comment by pedroslopez** [comment]
With this change, the `latest` tag now points to the latest alpha release, right? @evantahler

**Comment by evantahler** [comment]
Yeah - I added a note in the readme that folks should really pick a version number specifically. 

At some points in time, latest will be the mainline release, but most of the time probably point to an alpha.

**Pull request merged**
